
export const universities = [
  {
    "name": "Eulogio \"Amang\" Rodriguez Institute of Science and Technology",
    "location": "Manila",
    "province": "Metro Manila",
    "established": "1945",
    "type": "-- established (year)\n  Public",
    "students": "20000",
    "programs": "-- students (as string)\n  60",
    "description": "-- programs\n  A state university in Manila",
    "long_description": "Philippines",
    "subjects": "that offers a wide range of undergraduate and graduate programs in science",
    "image_url": "technology",
    "gallery_images": "education",
    "accreditation": "and more.",
    "campus_size": "The Eulogio \"Amang\" Rodriguez Institute of Science and Technology (EARIST) is a public university located in Sampaloc",
    "founded": "Manila. The university is known for its programs in science",
    "website": "technology",
    "phone": "and education. It was founded in 1945 by the late President Manuel L. Quezon.",
    "email": "ARRAY[Psychology",
    "address": "Criminology",
    "facilities": "Computer Science",
    "amenities": "Hospitality Management",
    "achievements": "Business Administration",
    "quickfacts": "Office Administration",
    "admission_requirements": "Information Technology",
    "application_process": "Industrial Technology",
    "admission_status": "Applied Physics",
    "admission_deadline": "Architecture",
    "academic_semester_start": "Fine Arts",
    "academic_semester_end": "Education",
    "academic_application_deadline": "Special Needs Education",
    "ranking_source": "Chemical Engineering",
    "ranking_details": "Civil Engineering",
    "map_location_lat": "Electrical Engineering",
    "map_location_lng": "Electronics and Communication Engineering"
  },
  {
    "name": "Marikina Polytechnic College",
    "location": "Marikina City",
    "province": "Metro Manila",
    "established": "1947",
    "type": "-- established (year)\n  Public",
    "students": "5000",
    "programs": "-- students (as string)\n  25",
    "description": "-- programs\n  A public polytechnic college in Marikina City",
    "long_description": "Philippines. It is one of the premier polytechnic colleges in the country.",
    "subjects": "Marikina Polytechnic College is a public polytechnic college in Marikina City",
    "image_url": "Philippines. It was established in 1947. The college is funded and operated by the City Government of Marikina.",
    "gallery_images": "ARRAY[Technical Vocational Teacher Education",
    "accreditation": "Industrial Technology",
    "campus_size": "Electronics Engineering",
    "founded": "Entrepreneurship",
    "website": "Education",
    "phone": "Technology]::text[]",
    "email": "-- subjects (inferred from programs)\n  https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "address": "-- image_url\n  ARRAY[https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "facilities": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "amenities": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "achievements": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg]::text[]",
    "quickfacts": "-- gallery_images\n  ARRAY[Accredited by the Accrediting Agency of Chartered Colleges and Universities in the Philippines (AACCUP).]::text[]",
    "admission_requirements": "-- accreditation\n  NULL",
    "application_process": "-- campus_size (no specific data)\n  1947",
    "admission_status": "-- founded\n  https://mpc.edu.ph/",
    "admission_deadline": "info@mpc.edu.ph",
    "academic_semester_start": "(02) 8942 9736",
    "academic_semester_end": "Shoe Ave",
    "academic_application_deadline": "Sto. Niño",
    "ranking_source": "Marikina",
    "ranking_details": "1800 Metro Manila",
    "map_location_lat": "ARRAY[Main Library",
    "map_location_lng": "College of Technology"
  },
  {
    "name": "Philippine State College of Aeronautics",
    "location": "Pasay City",
    "province": "Metro Manila",
    "established": "1968",
    "type": "-- established (year)\n  Public",
    "students": "10000",
    "programs": "-- students (as string)\n  15",
    "description": "-- programs\n  A state college in the Philippines specializing in aviation and aeronautics.",
    "long_description": "The Philippine State College of Aeronautics is a state college in the Philippines with a curriculum focused on aviation and aeronautics. Its main campus is in Pasay City. The college has other campuses in the Philippines.",
    "subjects": "ARRAY[Aeronautical Engineering",
    "image_url": "Information Management",
    "gallery_images": "Aviation Information Technology",
    "accreditation": "Air Transportation",
    "campus_size": "Aircraft Maintenance Technology",
    "founded": "Aviation Electronics Technology",
    "website": "Aviation Communication",
    "phone": "Aviation Tourism",
    "email": "Aviation Logistics",
    "address": "Aviation Safety and Security Management",
    "facilities": "Public Administration",
    "amenities": "Aeronautical Management]::text[]",
    "achievements": "-- subjects (inferred from programs)\n  https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "quickfacts": "-- image_url\n  ARRAY[https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "admission_requirements": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "application_process": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "admission_status": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg]::text[]",
    "admission_deadline": "-- gallery_images\n  ARRAY[ISO 9001:2015 Certified",
    "academic_semester_start": "Accredited by the Accrediting Agency of Chartered Colleges and Universities in the Philippines (AACCUP).]::text[]",
    "academic_semester_end": "-- accreditation\n  NULL",
    "academic_application_deadline": "-- campus_size (no specific data)\n  1968",
    "ranking_source": "-- founded\n  https://www.philsca.edu.ph/",
    "ranking_details": "info@philsca.edu.ph",
    "map_location_lat": "(02) 8521 6811",
    "map_location_lng": "Piccio Garden"
  },
  {
    "name": "Philippine Normal University",
    "location": "Manila",
    "province": "Metro Manila",
    "established": "1901",
    "type": "-- established (year)\n  Public",
    "students": "15000",
    "programs": "-- students (as string)\n  50",
    "description": "-- programs\n  The National Center for Teacher Education",
    "long_description": "a premier institution for teacher education in the Philippines.",
    "subjects": "The Philippine Normal University is a public research university in Manila",
    "image_url": "Philippines. It was established in 1901 through Act No. 74 of the Philippine Commission as the Philippine Normal School",
    "gallery_images": "a teacher training institution. It is the first and oldest institution for teacher education in the country.",
    "accreditation": "ARRAY[Teacher Education",
    "campus_size": "Elementary Education",
    "founded": "Secondary Education",
    "website": "Early Childhood Education",
    "phone": "Library and Information Science",
    "email": "Physical Education",
    "address": "Technology and Livelihood Education",
    "facilities": "Educational Leadership and Management",
    "amenities": "English Language Education",
    "achievements": "Mathematics Education",
    "quickfacts": "Science Education",
    "admission_requirements": "Social Studies Education",
    "application_process": "Values Education]::text[]",
    "admission_status": "-- subjects (inferred from programs)\n  https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "admission_deadline": "-- image_url (first from gallery)\n  ARRAY[https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "academic_semester_start": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "academic_semester_end": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "academic_application_deadline": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg]::text[]",
    "ranking_source": "-- gallery_images\n  ARRAY[Center of Excellence in Teacher Education]::text[]",
    "ranking_details": "-- accreditation\n  NULL",
    "map_location_lat": "-- campus_size\n  1901",
    "map_location_lng": "-- founded\n  https://www.pnu.edu.ph/"
  },
  {
    "name": "Rizal Technological University",
    "location": "Mandaluyong City",
    "province": "Metro Manila",
    "established": "1969",
    "type": "-- established (year)\n  Public",
    "students": "25000",
    "programs": "-- students (as string)\n  90",
    "description": "-- programs\n  A state university in the Philippines that is mandated to provide instruction and professional training in science",
    "long_description": "technology and other areas.",
    "subjects": "Rizal Technological University (RTU) is a state university located at Mandaluyong",
    "image_url": "Philippines. It was established on July 11",
    "gallery_images": "1969 as the College of Rizal",
    "accreditation": "part of the University of Rizal System",
    "campus_size": "before it was granted autonomy in 1975. The university is the first educational institution in the country to use cooperative education as a curriculum plan which is recognized by various industries",
    "founded": "businesses and agencies all over the country.",
    "website": "ARRAY[Engineering",
    "phone": "Architecture",
    "email": "Computer Studies",
    "address": "Business",
    "facilities": "Education",
    "amenities": "Arts and Sciences",
    "achievements": "Human Kinetics",
    "quickfacts": "Astronomy]::text[]",
    "admission_requirements": "-- subjects (inferred from programs)\n  https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "application_process": "-- image_url\n  ARRAY[https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "admission_status": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "admission_deadline": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg",
    "academic_semester_start": "https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg]::text[]",
    "academic_semester_end": "-- gallery_images\n  ARRAY[ISO 9001:2015 Certified",
    "academic_application_deadline": "Accredited by the Accrediting Agency of Chartered Colleges and Universities in the Philippines (AACCUP).]::text[]",
    "ranking_source": "-- accreditation\n  NULL",
    "ranking_details": "-- campus_size\n  1969",
    "map_location_lat": "-- founded\n  https://www.rtu.edu.ph/",
    "map_location_lng": "(02) 8534 8267"
  },
  {
    "name": "University of the Philippines Diliman",
    "location": "Quezon City",
    "province": "Metro Manila",
    "established": "1949",
    "type": "-- established (year)\n  Public",
    "students": "22000",
    "programs": "-- students (as string)\n  247",
    "description": "-- programs\n  The flagship campus of the University of the Philippines System",
    "long_description": "offering a wide range of undergraduate and graduate programs.",
    "subjects": "The University of the Philippines Diliman",
    "image_url": "coeval with the University of the Philippines",
    "gallery_images": "was established on June 18",
    "accreditation": "1908 through Act No. 1870 of the Philippine Assembly. The university was created to provide advanced instruction in literature",
    "campus_size": "philosophy",
    "founded": "the sciences",
    "website": "and arts",
    "phone": "and to give professional and technical training to deserving students.",
    "email": "ARRAY[Architecture",
    "address": "Business Administration",
    "facilities": "Education",
    "amenities": "Engineering",
    "achievements": "Fine Arts",
    "quickfacts": "Home Economics",
    "admission_requirements": "Library and Information Science",
    "application_process": "Mass Communication",
    "admission_status": "Music",
    "admission_deadline": "Public Administration",
    "academic_semester_start": "Science",
    "academic_semester_end": "Social Sciences and Philosophy",
    "academic_application_deadline": "Social Work",
    "ranking_source": "Statistics",
    "ranking_details": "Economics",
    "map_location_lat": "Human Kinetics",
    "map_location_lng": "Islamic Studies"
  },
  {
    "name": "University of the Philippines Manila",
    "location": "Manila",
    "province": "Metro Manila",
    "established": "1905",
    "type": "-- established (year)\n  Public",
    "students": "10000",
    "programs": "-- students (as string)\n  50",
    "description": "-- programs (placeholder)\n  The premier state university in the Philippines in the fields of health and medical sciences.",
    "long_description": "The University of the Philippines Manila is a public",
    "subjects": "research university in Manila",
    "image_url": "Philippines. It is the oldest of the seven constituent universities of the University of the Philippines System",
    "gallery_images": "even predating the founding of UP by three years. It is the national university of the Philippines.",
    "accreditation": "ARRAY[Occupational Therapy",
    "campus_size": "Physical Therapy",
    "founded": "Speech Pathology",
    "website": "Clinical Audiology",
    "phone": "Rehabilitation Science",
    "email": "Applied Physics",
    "address": "Behavioral Sciences",
    "facilities": "Biochemistry",
    "amenities": "Biology",
    "achievements": "Computer Science",
    "quickfacts": "Development Studies",
    "admission_requirements": "Organizational Communication",
    "application_process": "Philippine Arts",
    "admission_status": "Political Science",
    "admission_deadline": "Social Science",
    "academic_semester_start": "Management",
    "academic_semester_end": "Health Policy Studies",
    "academic_application_deadline": "Health Informatics",
    "ranking_source": "Dentistry",
    "ranking_details": "Medicine",
    "map_location_lat": "Nursing",
    "map_location_lng": "Pharmacy"
  }
];
export const academic_programs = [];
