-- Update university acronyms and program keywords

-- Polytechnic University of the Philippines (PUP)
UPDATE universities SET acronym = 'PUP' WHERE name = 'Polytechnic University of the Philippines';
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'HRM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Human Resource Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'MM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Marketing Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSIE'] WHERE program_name = 'Bachelor of Science in Industrial Engineering' AND university_id = 1;

-- Polytechnic University of the Philippines Commonwealth (PUPQC)
UPDATE universities SET acronym = 'PUPQC' WHERE name = 'Polytechnic University of the Philippines Commonwealth';
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 101;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'MM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Marketing Management' AND university_id = 101;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'HRM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Human Resource Management' AND university_id = 101;

-- Polytechnic University of the Philippines Parañaque (PUP-Parañaque)
UPDATE universities SET acronym = 'PUP-Parañaque' WHERE name = 'Polytechnic University of the Philippines Parañaque';
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = 102;
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management' AND university_id = 102;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 102;

-- Polytechnic University of the Philippines San Juan (PUPSJ)
UPDATE universities SET acronym = 'PUPSJ' WHERE name = 'Polytechnic University of the Philippines San Juan';
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy' AND university_id = 104;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education major in English' AND university_id = 104;
UPDATE academic_programs SET keywords = ARRAY['BSENTREP'] WHERE program_name = 'Bachelor of Science in Entrepreneurship' AND university_id = 104;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'FM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Financial Management' AND university_id = 104;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 104;
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management' AND university_id = 104;
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology' AND university_id = 104;

-- Polytechnic University of the Philippines Taguig (PUPT)
UPDATE universities SET acronym = 'PUPT' WHERE name = 'Polytechnic University of the Philippines Taguig';
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSAM'] WHERE program_name = 'Bachelor of Science in Applied Mathematics' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSBA'] WHERE program_name = 'Bachelor of Science in Business Administration' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSENTREP'] WHERE program_name = 'Bachelor of Science in Entrepreneurship' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = 105;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor in Secondary Education' AND university_id = 105;

-- Rizal Technological University (RTU)
UPDATE universities SET acronym = 'RTU' WHERE name = 'Rizal Technological University';
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSIE'] WHERE program_name = 'Bachelor of Science in Industrial Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSBA'] WHERE program_name = 'Bachelor of Science in Business Administration' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology' AND university_id = (SELECT id FROM universities WHERE name = 'Rizal Technological University');

-- Rizal Technological University - Pasig Campus (RTU-Pasig)
UPDATE universities SET acronym = 'RTU-Pasig' WHERE name = 'Rizal Technological University - Pasig Campus';
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = 106;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 106;
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education' AND university_id = 106;

-- Technological University of the Philippines (TUP)
UPDATE universities SET acronym = 'TUP' WHERE name = 'Technological University of the Philippines';
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSIS'] WHERE program_name = 'Bachelor of Science in Information System' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 2;
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = 2;

-- Technological University of the Philippines - Taguig Campus (TUP-T)
UPDATE universities SET acronym = 'TUP-T' WHERE name = 'Technological University of the Philippines - Taguig Campus';
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = 107;
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = 107;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = 107;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = 107;
UPDATE academic_programs SET keywords = ARRAY['BSES'] WHERE program_name = 'Bachelor of Science in Environmental Science' AND university_id = 107;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 107;

-- Eulogio "Amang" Rodriguez Institute of Science and Technology (EARIST)
UPDATE universities SET acronym = 'EARIST' WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology';
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCRIM'] WHERE program_name = 'Bachelor of Science in Criminology' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSBA'] WHERE program_name = 'Bachelor of Science in Business Administration' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSOA'] WHERE program_name = 'Bachelor of Science in Office Administration' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor in Secondary Education' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCHE'] WHERE program_name = 'Bachelor of Science in Chemical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics and Communication Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSN'] WHERE program_name = 'Bachelor of Science in Nursing' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');

-- Marikina Polytechnic College (MPC)
UPDATE universities SET acronym = 'MPC' WHERE name = 'Marikina Polytechnic College';
UPDATE academic_programs SET keywords = ARRAY['BTVTE'] WHERE program_name = 'Bachelor of Technical Vocational Teacher Education' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');
UPDATE academic_programs SET keywords = ARRAY['BIT'] WHERE program_name = 'Bachelor of Industrial Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');
UPDATE academic_programs SET keywords = ARRAY['BSENTREP'] WHERE program_name = 'Bachelor of Science in Entrepreneurship' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');

-- Philippine State College of Aeronautics (PhilSCA)
UPDATE universities SET acronym = 'PhilSCA' WHERE name = 'Philippine State College of Aeronautics';
UPDATE academic_programs SET keywords = ARRAY['BSAE'] WHERE program_name = 'Bachelor of Science in Aeronautical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine State College of Aeronautics');
UPDATE academic_programs SET keywords = ARRAY['BSAIT'] WHERE program_name = 'Bachelor of Science in Aviation Information Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine State College of Aeronautics');
UPDATE academic_programs SET keywords = ARRAY['BSAMT'] WHERE program_name = 'Bachelor of Science in Aircraft Maintenance Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine State College of Aeronautics');

-- Pamantasan ng Lungsod ng Maynila (PLM)
UPDATE universities SET acronym = 'PLM' WHERE name = 'Pamantasan ng Lungsod ng Maynila';
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture (BSARCH)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy (BS ACCTG)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'FM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Financial Management (BSBA-FM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'HRM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Human Resource Management (BSBA-HRM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'OM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Operations Management (BSBA-OM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'MM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Marketing Management (BSBA-MM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management (BSHM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSTM'] WHERE program_name = 'Bachelor of Science in Tourism Management (BSTM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Elementary Education - with specialization in Pre-School Education (BEEd-PSE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education - Major in School Physical Education (BPE-SPE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Biological Sciences (BSE-BS)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in English (BSEd-Eng)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Filipino (BSEd-Fil)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Mathematics (BSEd-Math)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Social Studies (BSEd-SS)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCHE'] WHERE program_name = 'Bachelor of Science in Chemical Engineering (BSCHE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering (BSCE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering (BSCpE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science (BSCS)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering (BSEE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering (BSECE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology (BSIT)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering (BSME)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSN'] WHERE program_name = 'Bachelor of Science in Nursing (BSN)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSPT'] WHERE program_name = 'Bachelor of Science in Physical Therapy (BSPT)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology (BS Bio)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCHEM'] WHERE program_name = 'Bachelor of Science in Chemistry (BS Chem)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSMATH'] WHERE program_name = 'Bachelor of Science in Mathematics (BS Math)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology (BSPSY)' AND university_id = 3;

-- Philippine Normal University (PNU)
UPDATE universities SET acronym = 'PNU' WHERE name = 'Philippine Normal University';
UPDATE academic_programs SET keywords = ARRAY['BLIS'] WHERE program_name = 'Bachelor of Library and Information Science' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine Normal University');
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine Normal University');
UPDATE academic_programs SET keywords = ARRAY['BTLE'] WHERE program_name = 'Bachelor of Technology and Livelihood Education' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine Normal University');

-- University of the Philippines Diliman (UPD)
UPDATE universities SET acronym = 'UPD' WHERE name = 'University of the Philippines Diliman';
UPDATE academic_programs SET keywords = ARRAY['BSLA'] WHERE program_name = 'Bachelor of Landscape Architecture' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBA'] WHERE program_name = 'Bachelor of Science in Business Administration' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBAA'] WHERE program_name = 'Bachelor of Science in Business Administration and Accountancy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BEED'] WHERE program_name = 'Bachelor of Elementary Education' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSED'] WHERE program_name = 'Bachelor of Secondary Education' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCHE'] WHERE program_name = 'Bachelor of Science in Chemical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics & Communications Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSGE'] WHERE program_name = 'Bachelor of Science in Geodetic Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSIE'] WHERE program_name = 'Bachelor of Science in Industrial Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMetE'] WHERE program_name = 'Bachelor of Science in Metallurgical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSEM'] WHERE program_name = 'Bachelor of Science in Mining Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMatE'] WHERE program_name = 'Bachelor of Science in Materials Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BFA'] WHERE program_name = 'Bachelor of Fine Arts' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSID'] WHERE program_name = 'Bachelor of Science in Interior Design' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BLIS'] WHERE program_name = 'Bachelor of Library & Information Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BCA'] WHERE program_name = 'Bachelor of Arts in Broadcast Communication' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAJ'] WHERE program_name = 'Bachelor of Arts in Journalism' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BACR'] WHERE program_name = 'Bachelor of Arts in Communication Research' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAF'] WHERE program_name = 'Bachelor of Arts in Film' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BM'] WHERE program_name = 'Bachelor of Music' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAPA'] WHERE program_name = 'Bachelor of Arts (Public Administration)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCHEM'] WHERE program_name = 'Bachelor of Science in Chemistry' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMATH'] WHERE program_name = 'Bachelor of Science in Mathematics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMBB'] WHERE program_name = 'Bachelor of Science in Molecular Biology & Biotechnology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSGEO'] WHERE program_name = 'Bachelor of Science in Geology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSAP'] WHERE program_name = 'Bachelor of Science in Applied Physics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSPHY'] WHERE program_name = 'Bachelor of Science in Physics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAA'] WHERE program_name = 'Bachelor of Arts (Anthropology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSG'] WHERE program_name = 'Bachelor of Science (Geography)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAH'] WHERE program_name = 'Bachelor of Arts (History)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAL'] WHERE program_name = 'Bachelor of Arts (Linguistics)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAP'] WHERE program_name = 'Bachelor of Arts (Philosophy)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAPS'] WHERE program_name = 'Bachelor of Arts (Political Science)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAPSY'] WHERE program_name = 'Bachelor of Arts (Psychology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSPSY'] WHERE program_name = 'Bachelor of Science (Psychology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAS'] WHERE program_name = 'Bachelor of Arts (Sociology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCD'] WHERE program_name = 'Bachelor of Science in Community Development' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSSW'] WHERE program_name = 'Bachelor of Science in Social Work' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSS'] WHERE program_name = 'Bachelor of Science (Statistics)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BABE'] WHERE program_name = 'Bachelor of Arts (Business Economics)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAAP'] WHERE program_name = 'Bachelor of Arts (Applied Psychology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBM'] WHERE program_name = 'Bachelor of Science in Business Management' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAAS'] WHERE program_name = 'Bachelor of Arts (Art Studies)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BACL'] WHERE program_name = 'Bachelor of Arts (Comparative Literature)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BACW'] WHERE program_name = 'Bachelor of Arts (Creative Writing)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAES'] WHERE program_name = 'Bachelor of Arts (English Studies)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAEL'] WHERE program_name = 'Bachelor of Arts (European Languages)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAAP'] WHERE program_name = 'Bachelor of Arts (Araling Pilipino)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAF'] WHERE program_name = 'Bachelor of Arts (Filipino)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAMPS'] WHERE program_name = 'Bachelor of Arts (Malikhaing Pagsulat sa Filipino)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BASC'] WHERE program_name = 'Bachelor of Arts (Speech Communication)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BATA'] WHERE program_name = 'Bachelor of Arts (Theatre Arts)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BST'] WHERE program_name = 'Bachelor of Science in Tourism' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBE'] WHERE program_name = 'Bachelor of Science in Business Economics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Science in Economics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCT'] WHERE program_name = 'Bachelor of Science in Clothing Technology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSFLCD'] WHERE program_name = 'Bachelor of Science in Family Life & Child Development' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCN'] WHERE program_name = 'Bachelor of Science in Community Nutrition' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSFT'] WHERE program_name = 'Bachelor of Science in Food Technology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSHE'] WHERE program_name = 'Bachelor of Science in Home Economics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSHRIM'] WHERE program_name = 'Bachelor of Science in Hotel, Restaurant & Institution Management' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSS'] WHERE program_name = 'Bachelor of Sports Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');

-- University of the Philippines Manila (UPM)
UPDATE universities SET acronym = 'UPM' WHERE name = 'University of the Philippines Manila';
UPDATE academic_programs SET keywords = ARRAY['BSOT'] WHERE program_name = 'Bachelor of Science in Occupational Therapy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSPT'] WHERE program_name = 'Bachelor of Science in Physical Therapy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSSP'] WHERE program_name = 'Bachelor of Science in Speech Pathology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSAP'] WHERE program_name = 'Bachelor of Science in Applied Physics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BABS'] WHERE program_name = 'Bachelor of Arts in Behavioral Sciences' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSB'] WHERE program_name = 'Bachelor of Science in Biochemistry' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BADS'] WHERE program_name = 'Bachelor of Arts in Development Studies' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BAOC'] WHERE program_name = 'Bachelor of Arts in Organizational Communication' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BAPA'] WHERE program_name = 'Bachelor of Arts in Philippine Arts' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BAPS'] WHERE program_name = 'Bachelor of Arts in Political Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BASS'] WHERE program_name = 'Bachelor of Arts in Social Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['DDM'] WHERE program_name = 'Doctor of Dental Medicine' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSBMS'] WHERE program_name = 'Bachelor of Science in Basic Medical Sciences' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['MD'] WHERE program_name = 'Doctor of Medicine' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSN'] WHERE program_name = 'Bachelor of Science in Nursing' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSP'] WHERE program_name = 'Bachelor of Science in Pharmacy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSIP'] WHERE program_name = 'Bachelor of Science in Industrial Pharmacy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSPH'] WHERE program_name = 'Bachelor of Science in Public Health' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
-- Complete keywords for PUP Main
UPDATE academic_programs SET keywords = ARRAY['DPA'] WHERE program_name = 'Doctor in Public Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DBA'] WHERE program_name = 'Doctor in Business Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DEM'] WHERE program_name = 'Doctor in Engineering Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DPE'] WHERE program_name = 'Doctor of Philsophy in Education Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MC'] WHERE program_name = 'Master in Communication' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MBA'] WHERE program_name = 'Master in Business Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MAEM'] WHERE program_name = 'Master of Arts in Education Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MIT'] WHERE program_name = 'Master in Information Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MPA'] WHERE program_name = 'Master in Public Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MSCM'] WHERE program_name = 'Master of Science in Construction Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['PBDIT'] WHERE program_name = 'Post Baccalaureate Diploma in Information Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Science in Entrepreneurship' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAB'] WHERE program_name = 'Bachelor of Arts in Broadcasting' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBAHRM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Human Resource Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBAMM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Marketing Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSOA'] WHERE program_name = 'Bachelor of Science in Office Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSTM'] WHERE program_name = 'Bachelor of Science in Tourism Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BPA'] WHERE program_name = 'Bachelor of Public Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBAFM'] WHERE program_name = 'Bachelor of Science in Business Administration Major in Financial Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSMA'] WHERE program_name = 'Bachelor of Science in Management Accounting' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSID'] WHERE program_name = 'Bachelor of Science in Interior Design' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEP'] WHERE program_name = 'Bachelor of Science in Environmental Planning' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAELS'] WHERE program_name = 'Bachelor of Arts in English Language Studies' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAF'] WHERE program_name = 'Bachelor of Arts in Filipinology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BALCS'] WHERE program_name = 'Bachelor of Arts in Literary and Cultural Studies' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAP'] WHERE program_name = 'Bachelor of Arts in Philosophy' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BPATA'] WHERE program_name = 'Bachelor of Performing Arts major in Theater Arts' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DBA'] WHERE program_name = 'Doctor in Business Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MBA'] WHERE program_name = 'Master in Business Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBAHRM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Human Resource Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBAMM'] WHERE program_name = 'Bachelor of Science in Business Administration major in Marketing Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Science in Entrepreneurship' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSOA'] WHERE program_name = 'Bachelor of Science in Office Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAPR'] WHERE program_name = 'Bachelor in Advertising and Public Relations' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAB'] WHERE program_name = 'Bachelor of Arts in Broadcasting' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BACR'] WHERE program_name = 'Bachelor of Arts in Communication Research' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAJ'] WHERE program_name = 'Bachelor of Arts in Journalism' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DPEM'] WHERE program_name = 'Doctor of Philsophy in Education Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MAEM'] WHERE program_name = 'Master of Arts in Education Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MBE'] WHERE program_name = 'Master in Business Education' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MLIS'] WHERE program_name = 'Master in Library and Information Science' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MAELT'] WHERE program_name = 'Master of Arts in English Language Teaching' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MAEDME'] WHERE program_name = 'Master of Arts in Education major in Mathematics Education' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MAPES'] WHERE program_name = 'Master of Arts in Physical Education and Sports' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MAEDTCA'] WHERE program_name = 'Master of Arts in Education major in Teaching in the Challenged Areas' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['PBDE'] WHERE program_name = 'Post-Baccalaureate Diploma in Education' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BTLEHE'] WHERE program_name = 'Bachelor of Technology and Livelihood Education major in Home Economics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BTLEIA'] WHERE program_name = 'Bachelor of Technology and Livelihood Education major in Industrial Arts' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BTLEICT'] WHERE program_name = 'Bachelor of Technology and Livelihood Education major in Information and Communication Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BLIS'] WHERE program_name = 'Bachelor of Library and Information Science' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEDE'] WHERE program_name = 'Bachelor of Secondary Education major in English' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEDM'] WHERE program_name = 'Bachelor of Secondary Education major in Mathematics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEDS'] WHERE program_name = 'Bachelor of Secondary Education major in Science' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEDF'] WHERE program_name = 'Bachelor of Secondary Education major in Filipino' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEDSS'] WHERE program_name = 'Bachelor of Secondary Education major in Social Studies' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BEED'] WHERE program_name = 'Bachelor of Elementary Education' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BECED'] WHERE program_name = 'Bachelor of Early Childhood Education' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSCPE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSIE'] WHERE program_name = 'Bachelor of Science in Industrial Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSRE'] WHERE program_name = 'Bachelor of Science in Railway Engineering' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSESS'] WHERE program_name = 'Bachelor of Science in Exercises and Sports' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['JD'] WHERE program_name = 'Juris Doctor' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DPA'] WHERE program_name = 'Doctor in Public Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['MPA'] WHERE program_name = 'Master in Public Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAPS'] WHERE program_name = 'Bachelor of Arts in Political Science' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAPE'] WHERE program_name = 'Bachelor of Arts in Political Economy' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAIS'] WHERE program_name = 'Bachelor of Arts in International Studies' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BPA'] WHERE program_name = 'Bachelor of Public Administration' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAH'] WHERE program_name = 'Bachelor of Arts in History' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BAS'] WHERE program_name = 'Bachelor of Arts in Sociology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSC'] WHERE program_name = 'Bachelor of Science in Cooperatives' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Science in Economics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSFT'] WHERE program_name = 'Bachelor of Science Food Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSAM'] WHERE program_name = 'Bachelor of Science in Applied Mathematics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSCHEM'] WHERE program_name = 'Bachelor of Science in Chemistry' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSM'] WHERE program_name = 'Bachelor of Science in Mathematics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSND'] WHERE program_name = 'Bachelor of Science in Nutrition and Dietetics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSP'] WHERE program_name = 'Bachelor of Science in Physics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSS'] WHERE program_name = 'Bachelor of Science in Statistics' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSTM'] WHERE program_name = 'Bachelor of Science in Tourism Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['BSTRM'] WHERE program_name = 'Bachelor of Science in Transportation Management' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DCET'] WHERE program_name = 'Diploma in Computer Engineering Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DEET'] WHERE program_name = 'Diploma in Electrical Engineering Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DECET'] WHERE program_name = 'Diploma in Electronics Engineering Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DICT'] WHERE program_name = 'Diploma in Information Communication Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DMET'] WHERE program_name = 'Diploma in Mechanical Engineering Technology' AND university_id = 1;
UPDATE academic_programs SET keywords = ARRAY['DOMT'] WHERE program_name = 'Diploma in Office Management' AND university_id = 1;

-- Eulogio "Amang" Rodriguez Institute of Science and Technology (EARIST)
UPDATE universities SET acronym = 'EARIST' WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology';
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCRIM'] WHERE program_name = 'Bachelor of Science in Criminology' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSBA'] WHERE program_name = 'Bachelor of Science in Business Administration' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSOA'] WHERE program_name = 'Bachelor of Science in Office Administration' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor in Secondary Education' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCHE'] WHERE program_name = 'Bachelor of Science in Chemical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics and Communication Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSN'] WHERE program_name = 'Bachelor of Science in Nursing' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BTVTE'] WHERE program_name = 'Bachelor in Technology and Livelihood Education' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');
UPDATE academic_programs SET keywords = ARRAY['BSNED'] WHERE program_name = 'Bachelor in Special Needs Education' AND university_id = (SELECT id FROM universities WHERE name = 'Eulogio "Amang" Rodriguez Institute of Science and Technology');

-- Marikina Polytechnic College (MPC)
UPDATE universities SET acronym = 'MPC' WHERE name = 'Marikina Polytechnic College';
UPDATE academic_programs SET keywords = ARRAY['BTVTE'] WHERE program_name = 'Bachelor of Technical Vocational Teacher Education' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');
UPDATE academic_programs SET keywords = ARRAY['BIT'] WHERE program_name = 'Bachelor of Industrial Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');
UPDATE academic_programs SET keywords = ARRAY['BSENTREP'] WHERE program_name = 'Bachelor of Science in Entrepreneurship' AND university_id = (SELECT id FROM universities WHERE name = 'Marikina Polytechnic College');

-- Philippine State College of Aeronautics (PhilSCA)
UPDATE universities SET acronym = 'PhilSCA' WHERE name = 'Philippine State College of Aeronautics';
UPDATE academic_programs SET keywords = ARRAY['BSAE'] WHERE program_name = 'Bachelor of Science in Aeronautical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine State College of Aeronautics');
UPDATE academic_programs SET keywords = ARRAY['BSAIT'] WHERE program_name = 'Bachelor of Science in Aviation Information Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine State College of Aeronautics');
UPDATE academic_programs SET keywords = ARRAY['BSAMT'] WHERE program_name = 'Bachelor of Science in Aircraft Maintenance Technology' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine State College of Aeronautics');

-- Pamantasan ng Lungsod ng Maynila (PLM)
UPDATE universities SET acronym = 'PLM' WHERE name = 'Pamantasan ng Lungsod ng Maynila';
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture (BSARCH)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSA'] WHERE program_name = 'Bachelor of Science in Accountancy (BS ACCTG)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'FM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Financial Management (BSBA-FM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'HRM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Human Resource Management (BSBA-HRM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'OM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Operations Management (BSBA-OM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBA', 'MM'] WHERE program_name = 'Bachelor of Science in Business Administration - Major in Marketing Management (BSBA-MM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSHM'] WHERE program_name = 'Bachelor of Science in Hospitality Management (BSHM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSTM'] WHERE program_name = 'Bachelor of Science in Tourism Management (BSTM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Elementary Education - with specialization in Pre-School Education (BEEd-PSE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education - Major in School Physical Education (BPE-SPE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Biological Sciences (BSE-BS)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in English (BSEd-Eng)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Filipino (BSEd-Fil)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Mathematics (BSEd-Math)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Secondary Education - with specialization in Social Studies (BSEd-SS)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCHE'] WHERE program_name = 'Bachelor of Science in Chemical Engineering (BSCHE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering (BSCE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering (BSCpE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science (BSCS)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering (BSEE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics Engineering (BSECE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSIT'] WHERE program_name = 'Bachelor of Science in Information Technology (BSIT)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering (BSME)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSN'] WHERE program_name = 'Bachelor of Science in Nursing (BSN)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSPT'] WHERE program_name = 'Bachelor of Science in Physical Therapy (BSPT)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology (BS Bio)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSCHEM'] WHERE program_name = 'Bachelor of Science in Chemistry (BS Chem)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSMATH'] WHERE program_name = 'Bachelor of Science in Mathematics (BS Math)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSPSYCH'] WHERE program_name = 'Bachelor of Science in Psychology (BSPSY)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSREM'] WHERE program_name = 'Bachelor in Real Estate Management (BREM)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSENTRE'] WHERE program_name = 'Bachelor of Science in Entrepreneurship (BSENTRE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSBE'] WHERE program_name = 'Bachelor of Science in Business Economics (BSBE)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BAC'] WHERE program_name = 'Bachelor of Arts in Communication (BAC)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BACPR'] WHERE program_name = 'Bachelor of Arts in Communication - Major in Public Relations (BAC-PR)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSSW'] WHERE program_name = 'Bachelor of Science in Social Work (BSSW)' AND university_id = 3;
UPDATE academic_programs SET keywords = ARRAY['BSPA'] WHERE program_name = 'Bachelor of Science in Public Administration' AND university_id = 3;

-- Philippine Normal University (PNU)
UPDATE universities SET acronym = 'PNU' WHERE name = 'Philippine Normal University';
UPDATE academic_programs SET keywords = ARRAY['BLIS'] WHERE program_name = 'Bachelor of Library and Information Science' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine Normal University');
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine Normal University');
UPDATE academic_programs SET keywords = ARRAY['BTLE'] WHERE program_name = 'Bachelor of Technology and Livelihood Education' AND university_id = (SELECT id FROM universities WHERE name = 'Philippine Normal University');

-- University of the Philippines Diliman (UPD)
UPDATE universities SET acronym = 'UPD' WHERE name = 'University of the Philippines Diliman';
UPDATE academic_programs SET keywords = ARRAY['BSLA'] WHERE program_name = 'Bachelor of Landscape Architecture' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSARCH'] WHERE program_name = 'Bachelor of Science in Architecture' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBA'] WHERE program_name = 'Bachelor of Science in Business Administration' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBAA'] WHERE program_name = 'Bachelor of Science in Business Administration and Accountancy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BEED'] WHERE program_name = 'Bachelor of Elementary Education' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSED'] WHERE program_name = 'Bachelor of Secondary Education' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCE'] WHERE program_name = 'Bachelor of Science in Civil Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCHE'] WHERE program_name = 'Bachelor of Science in Chemical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSEE'] WHERE program_name = 'Bachelor of Science in Electrical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSECE'] WHERE program_name = 'Bachelor of Science in Electronics & Communications Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSGE'] WHERE program_name = 'Bachelor of Science in Geodetic Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSIE'] WHERE program_name = 'Bachelor of Science in Industrial Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSME'] WHERE program_name = 'Bachelor of Science in Mechanical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMetE'] WHERE program_name = 'Bachelor of Science in Metallurgical Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSEM'] WHERE program_name = 'Bachelor of Science in Mining Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMatE'] WHERE program_name = 'Bachelor of Science in Materials Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCpE'] WHERE program_name = 'Bachelor of Science in Computer Engineering' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BFA'] WHERE program_name = 'Bachelor of Fine Arts' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSID'] WHERE program_name = 'Bachelor of Science in Interior Design' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BLIS'] WHERE program_name = 'Bachelor of Library & Information Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BCA'] WHERE program_name = 'Bachelor of Arts in Broadcast Communication' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAJ'] WHERE program_name = 'Bachelor of Arts in Journalism' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BACR'] WHERE program_name = 'Bachelor of Arts in Communication Research' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAF'] WHERE program_name = 'Bachelor of Arts in Film' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BM'] WHERE program_name = 'Bachelor of Music' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAPA'] WHERE program_name = 'Bachelor of Arts (Public Administration)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCHEM'] WHERE program_name = 'Bachelor of Science in Chemistry' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMATH'] WHERE program_name = 'Bachelor of Science in Mathematics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSMBB'] WHERE program_name = 'Bachelor of Science in Molecular Biology & Biotechnology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSGEO'] WHERE program_name = 'Bachelor of Science in Geology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSAP'] WHERE program_name = 'Bachelor of Science in Applied Physics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSPHY'] WHERE program_name = 'Bachelor of Science in Physics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAA'] WHERE program_name = 'Bachelor of Arts (Anthropology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSG'] WHERE program_name = 'Bachelor of Science (Geography)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAH'] WHERE program_name = 'Bachelor of Arts (History)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAL'] WHERE program_name = 'Bachelor of Arts (Linguistics)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAP'] WHERE program_name = 'Bachelor of Arts (Philosophy)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAPS'] WHERE program_name = 'Bachelor of Arts (Political Science)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAPSY'] WHERE program_name = 'Bachelor of Arts (Psychology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSPSY'] WHERE program_name = 'Bachelor of Science (Psychology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAS'] WHERE program_name = 'Bachelor of Arts (Sociology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCD'] WHERE program_name = 'Bachelor of Science in Community Development' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSSW'] WHERE program_name = 'Bachelor of Science in Social Work' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSS'] WHERE program_name = 'Bachelor of Science (Statistics)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BABE'] WHERE program_name = 'Bachelor of Arts (Business Economics)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAAP'] WHERE program_name = 'Bachelor of Arts (Applied Psychology)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBM'] WHERE program_name = 'Bachelor of Science in Business Management' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAAS'] WHERE program_name = 'Bachelor of Arts (Art Studies)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BACL'] WHERE program_name = 'Bachelor of Arts (Comparative Literature)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BACW'] WHERE program_name = 'Bachelor of Arts (Creative Writing)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAES'] WHERE program_name = 'Bachelor of Arts (English Studies)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAEL'] WHERE program_name = 'Bachelor of Arts (European Languages)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAAP'] WHERE program_name = 'Bachelor of Arts (Araling Pilipino)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAF'] WHERE program_name = 'Bachelor of Arts (Filipino)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BAMPS'] WHERE program_name = 'Bachelor of Arts (Malikhaing Pagsulat sa Filipino)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BASC'] WHERE program_name = 'Bachelor of Arts (Speech Communication)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BATA'] WHERE program_name = 'Bachelor of Arts (Theatre Arts)' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BST'] WHERE program_name = 'Bachelor of Science in Tourism' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSBE'] WHERE program_name = 'Bachelor of Science in Business Economics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSE'] WHERE program_name = 'Bachelor of Science in Economics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCT'] WHERE program_name = 'Bachelor of Science in Clothing Technology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSFLCD'] WHERE program_name = 'Bachelor of Science in Family Life & Child Development' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSCN'] WHERE program_name = 'Bachelor of Science in Community Nutrition' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSFT'] WHERE program_name = 'Bachelor of Science in Food Technology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSHE'] WHERE program_name = 'Bachelor of Science in Home Economics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSHRIM'] WHERE program_name = 'Bachelor of Science in Hotel, Restaurant & Institution Management' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BPE'] WHERE program_name = 'Bachelor of Physical Education' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');
UPDATE academic_programs SET keywords = ARRAY['BSS'] WHERE program_name = 'Bachelor of Sports Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Diliman');

-- University of the Philippines Manila (UPM)
UPDATE universities SET acronym = 'UPM' WHERE name = 'University of the Philippines Manila';
UPDATE academic_programs SET keywords = ARRAY['BSOT'] WHERE program_name = 'Bachelor of Science in Occupational Therapy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSPT'] WHERE program_name = 'Bachelor of Science in Physical Therapy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSSP'] WHERE program_name = 'Bachelor of Science in Speech Pathology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSAP'] WHERE program_name = 'Bachelor of Science in Applied Physics' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BABS'] WHERE program_name = 'Bachelor of Arts in Behavioral Sciences' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSB'] WHERE program_name = 'Bachelor of Science in Biochemistry' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSBIO'] WHERE program_name = 'Bachelor of Science in Biology' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSCS'] WHERE program_name = 'Bachelor of Science in Computer Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BADS'] WHERE program_name = 'Bachelor of Arts in Development Studies' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BAOC'] WHERE program_name = 'Bachelor of Arts in Organizational Communication' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BAPA'] WHERE program_name = 'Bachelor of Arts in Philippine Arts' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BAPS'] WHERE program_name = 'Bachelor of Arts in Political Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BASS'] WHERE program_name = 'Bachelor of Arts in Social Science' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['DDM'] WHERE program_name = 'Doctor of Dental Medicine' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSBMS'] WHERE program_name = 'Bachelor of Science in Basic Medical Sciences' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['MD'] WHERE program_name = 'Doctor of Medicine' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSN'] WHERE program_name = 'Bachelor of Science in Nursing' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSP'] WHERE program_name = 'Bachelor of Science in Pharmacy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSIP'] WHERE program_name = 'Bachelor of Science in Industrial Pharmacy' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
UPDATE academic_programs SET keywords = ARRAY['BSPH'] WHERE program_name = 'Bachelor of Science in Public Health' AND university_id = (SELECT id FROM universities WHERE name = 'University of the Philippines Manila');
